```{r}
#loading packages
library(dplyr)
library(tidyverse)
```
```{r}
#loading dataframe
raw_data <- as.data.frame(irltim)
```

```{r}
#data cleaning
cleaned_data <- raw_data %>%
  select(stu_id, math, sex,parent_educ, parent_support, school_id, percent_affluent, percent_disadvantaged, computer, book, shortage_math_teachers, location, year) %>%
  rename(
    ID = stu_id,
    Scores = math,
    Gender = sex,
    Parent_Educ=parent_educ,
    Parent_Support = parent_support,
    Computer_Access = computer,
    Book_Availability = book,
    Teacher_Shortage = shortage_math_teachers,
    School_Id = school_id,
    Percent_Affluent = percent_affluent,
    Percent_Disadvantaged = percent_disadvantaged,
    Location = location,
    Year = year
    
  )


cleaned_data <- cleaned_data %>%
  mutate(Book_Availability = case_when(
    Book_Availability %in% c("0-10 BOOKS", "NONE OR VERY FEW (0-10 BOOKS)") ~ "Few",
    Book_Availability %in% c("11-25 BOOKS", "ENOUGH TO FILL ONE SHELF (11-25 BOOKS)") ~ "Moderate",
    Book_Availability %in% c("26-100 BOOKS", "ENOUGH TO FILL ONE BOOKCASE (26-100 BOOKS)") ~ "Good",
    Book_Availability %in% c("101-200 BOOKS", "ENOUGH TO FILL TWO BOOKCASES (101-200 BOOKS)") ~ "Very Good",
    Book_Availability %in% c("MORE THAN 200", "ENOUGH TO FILL THREE OR MORE BOOKCASES (MORE THAN 200)") ~ "Excellent",
    TRUE ~ Book_Availability
  ))                                      


cleaned_data$Percent_Affluent <- dplyr::recode(cleaned_data$Percent_Affluent,
  "0 TO 10%" = "Low",
  "11 TO 25%" = "Moderate",
  "26 TO 50%" = "High",
  "MORE THAN 50%" = "Excellent"
)

cleaned_data$Percent_Disadvantaged<-dplyr::recode(cleaned_data$Percent_Disadvantaged,
                                         "0 TO 10%" = "Low",
                                        "11 TO 25%" = "Moderate",
                                        "26 TO 50%" = "High",
                                        "MORE THAN 50%" = "Severe"
)

cleaned_data$Teacher_Shortage<-dplyr::recode(cleaned_data$Teacher_Shortage,
  "NOT AT ALL" = "None",
  "A LITTLE"   = "Low",
  "SOME"       = "Moderate",
  "A LOT"       ="High"
)
                                      

cleaned_data$Location <- dplyr::recode(cleaned_data$Location,
  "URBAN, DENSELY POPULATED" = "Urban",
  "URBAN-DENSELY POPULATED" = "Urban",
  "SUBURBAN, ON FRINGE OF URBAN AREA" = "Suburban",
  "SUBURBAN-ON FRINGE OR OUTSKIRTS OF URBAN AREA" = "Suburban",
  "MEDIUM SIZE CITY OR LARGE TOWN" = "Large Town/City",
  "SMALL TOWN OR VILLAGE" = "Small Town/Village",
  "REMOTE RURAL" = "Remote Rural"
)

View(cleaned_data)

colSums(is.na(cleaned_data))
```

```{r}
#Data preprocessing
# Categorical variables (nominal, unordered)
cleaned_data$Gender <- as.factor(cleaned_data$Gender)
cleaned_data$Location <- as.factor(cleaned_data$Location)
cleaned_data$School_Id <- as.factor(cleaned_data$School_Id)
cleaned_data$Computer_Access <- as.factor(cleaned_data$Computer_Access)
cleaned_data$Year <- as.factor(cleaned_data$Year)


# Ordinal variables (ordered from low to high)
cleaned_data$Parent_Educ <- factor(cleaned_data$Parent_Educ,
                         levels = c("less than ISCED2", "ISCED2", "ISCED3", "ISCED4", "ISCED6", "ISCED7 or 8"),
                         ordered = TRUE)

cleaned_data$Parent_Support <- factor(cleaned_data$Parent_Support,
                            levels = c("LOW", "MEDIUM", "HIGH", "VERY HIGH"),
                            ordered = TRUE)

cleaned_data$Percent_Affluent <- factor(cleaned_data$Percent_Affluent,
                              levels = c("Low", "Moderate", "High", "Excellent"),
                              ordered = TRUE)

cleaned_data$Percent_Disadvantaged <- factor(cleaned_data$Percent_Disadvantaged,
                                   levels = c("Low", "Moderate", "High", "Severe"),
                                   ordered = TRUE)

cleaned_data$Book_Availability <- factor(cleaned_data$Book_Availability,
                               levels = c("Few", "Moderate", "Good", "Very Good", "Excellent"),
                               ordered = TRUE)

cleaned_data$Teacher_Shortage <- factor(cleaned_data$Teacher_Shortage,
                              levels = c("None", "Low", "Moderate", "High"),
                              ordered = TRUE)

cleaned_data$Year <- factor(cleaned_data$Year,
                              levels = c("2015","2019"),
                              ordered = TRUE)

str(cleaned_data)
valid_factors <- sapply(cleaned_data, function(x) !(is.factor(x) && nlevels(x) < 2))
cleaned_data_filtered <- cleaned_data[, valid_factors]
valid_factors
#model <- lm(Scores ~ Gender + Parent_Educ + Parent_Support + 
#            Percent_Affluent + Percent_Disadvantaged +
#            Computer_Access + Book_Availability + Teacher_Shortage + 
#            Location, Year, data=cleaned_data)
model<- lm(Scores ~ .-School_Id-ID-Year, data = cleaned_data_filtered)
summary(model)
```
```{r}
par(mfrow = c(2, 2))  # 4 plots in one view
plot(model)
```
```{r warning=FALSE}
install.packages("car")
library(car)
vif(model)
```




```{r}
# Cook’s distance
cooksd <- cooks.distance(model)
plot(cooksd, pch="*", cex=1.5, main="Cook’s Distance")
abline(h = 4/length(cooksd), col="red")

influential <- as.numeric(names(cooksd)[(cooksd > (4/length(cooksd)))])
cleaned_data_filtered[influential, ]
```

