# Data visualization

```{r}
#loading packages
library(dplyr)
library(tidyverse)
library(ggplot2)
library(sjPlot)
```


```{r}
load("irltim.Rdata")#loaded the Ireland math data
view(irltim)
```


```{r}
#Cleaned the raw data by renaming variables and its levels and named it as cleaned_data
#kept the original data as it is(irltim)
cleaned_data <- irltim %>%
  select(stu_id, math, sex,parent_educ, parent_support, school_id, percent_affluent, percent_disadvantaged, computer, book, shortage_math_teachers, location, year) %>%
  rename(
    ID = stu_id,
    Scores = math,
    Gender = sex,
    Parent_Educ=parent_educ,
    Parent_Support = parent_support,
    Computer_Access = computer,
    Book_Availability = book,
    Teacher_Shortage = shortage_math_teachers,
    School_Id = school_id,
    Percent_Affluent=percent_affluent,
    Percent_Disadvantaged = percent_disadvantaged,
    Location = location,
    Year = year
 )


cleaned_data <- cleaned_data %>%
  mutate(Book_Availability = case_when(
    Book_Availability %in% c("0-10 BOOKS", "NONE OR VERY FEW (0-10 BOOKS)") ~ "Few",
    Book_Availability %in% c("11-25 BOOKS", "ENOUGH TO FILL ONE SHELF (11-25 BOOKS)") ~ "Moderate",
    Book_Availability %in% c("26-100 BOOKS", "ENOUGH TO FILL ONE BOOKCASE (26-100 BOOKS)") ~ "Good",
    Book_Availability %in% c("101-200 BOOKS", "ENOUGH TO FILL TWO BOOKCASES (101-200 BOOKS)") ~ "Very Good",
    Book_Availability %in% c("MORE THAN 200", "ENOUGH TO FILL THREE OR MORE BOOKCASES (MORE THAN 200)") ~ "Excellent",
    TRUE ~ Book_Availability
  ))                                      

cleaned_data$Percent_Disadvantaged<-
  dplyr::recode(cleaned_data$Percent_Disadvantaged,
                         "0 TO 10%" = "Low",
                        "11 TO 25%" = "Moderate",
                        "26 TO 50%" = "High",
                    "MORE THAN 50%" = "Severe"
)

cleaned_data$Teacher_Shortage<-dplyr::recode(cleaned_data$Teacher_Shortage,
  "NOT AT ALL" = "None",
  "A LITTLE"   = "Low",
  "SOME"       = "Moderate",
  "A LOT"       ="High"
)
                                      

cleaned_data$Location <- dplyr::recode(cleaned_data$Location,
  "URBAN, DENSELY POPULATED" = "Urban",
  "URBAN-DENSELY POPULATED" = "Urban_1",
  "SUBURBAN, ON FRINGE OF URBAN AREA" = "Suburban",
  "SUBURBAN-ON FRINGE OR OUTSKIRTS OF URBAN AREA" = "Suburban_1",
  "MEDIUM SIZE CITY OR LARGE TOWN" = "Large Town/City",
  "SMALL TOWN OR VILLAGE" = "Small Town/Village",
  "REMOTE RURAL" = "Remote Rural"
  
)
cleaned_data$Percent_Affluent<- dplyr::recode(cleaned_data$Percent_Affluent,
                                        "0 TO 10%" = "Low",
                                        "11 TO 25%" = "Moderate",
                                        "26 TO 50%" = "High",
                                        "MORE THAN 50%" = "Excellent"
)

View(cleaned_data)
```


*Distribution of scores by year plot*
```{r}
#Data visualization where distribution of scores by year was seen first on the cleaned_data for eda purposes.
 ggplot(cleaned_data, aes(x = factor(Year), y = Scores, fill = factor(Year))) +
  geom_violin(color = "black", alpha = 0.7, trim = FALSE) +
  geom_boxplot(width = 0.1,fill="white")+
  scale_fill_manual(values = c("orange","brown"))+
  ggtitle("Distribution of Scores by Year") +
  xlab("Year") + 
  ylab("Scores") +
  theme_minimal()
```


*Computer Access vs Score based on Year*                   
```{r}
#here scores distribution were seen for each level YES and NO for each years. Here, the Gender were filled to understand their performance in each category.
ggplot(cleaned_data, aes(x = Computer_Access, y = Scores, fill = Gender)) +
  geom_boxplot(position = position_dodge2(preserve="single"), alpha=0.7,outlier.shape = 21, color = "black",varwidth=TRUE) +
  ggtitle('Computer Access vs Score based on Year and Gender') +
  scale_fill_manual(values = c("pink", "steelblue")) +
  facet_wrap(~Year)
```

*Distribution of Scores by Location and Gender*
```{r}
#Since levels such as Suburban_1, Suburban and Urban_1, Urban are same but differently named accordingly represented for separate years. here, the scores distribution is seen of students from different school location.

cleaned_data$Location<- factor(cleaned_data$Location,
                                  levels=c("Remote Rural","Small Town/Village",
                                  "Large Town/City", "Suburban_1", "Suburban",
                                  "Urban_1", "Urban"))
year2015<-cleaned_data %>% filter(Year == 2015)
year2019<-cleaned_data %>% filter(Year == 2019)

ggplot(year2015, aes(x = Gender, y = Scores, fill = Location)) + 
geom_boxplot(position = position_dodge2(preserve="single"), alpha=0.7,
             outlier.shape = 21, color = "black",varwidth=TRUE)+ 
ggtitle('Scores vs Location and Gender(2015)') + 
scale_fill_manual(values=c("navyblue","brown","yellow","lightgreen","lightblue"))+
theme(
    plot.title = element_text(size = 18, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
)
  
ggplot(year2019, aes(x = Gender, y = Scores, fill = Location)) + 
geom_boxplot(position = position_dodge2(preserve="single"), alpha=0.7,
             outlier.shape = 21, color = "black",varwidth=TRUE)+ 
ggtitle('Scores vs Location and Gender(2019)') + 
scale_fill_manual(values=c("red","orange","yellow","lightgreen","lightblue"))+
theme(
    plot.title = element_text(size = 18, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
) 
```

#Combined Plot of top 10 schools by gender dominance
```{r}
#selected 10 schools out of all schools who performed best.
top_10_schools <- cleaned_data %>%
  group_by(School_Id) %>%
  summarise(Mean_Score = mean(Scores, na.rm = TRUE)) %>%
  arrange(desc(Mean_Score)) %>%
  slice_head(n = 10)

#filtered the top 10 schools and assigned it to another variable 
top_data <- cleaned_data %>%
  filter(School_Id %in% top_10_schools$School_Id)

#select school type(Boys only/ Girls Only or Mixed)
school_type_top <- top_data %>%
  group_by(School_Id) %>%
  summarise(
    num_boys = sum(Gender == "BOY"),
    num_girls = sum(Gender == "GIRL")
  ) %>%
  mutate(
    School_Type = case_when(
      num_boys > 0 & num_girls == 0 ~ "Boys Only",
      num_girls > 0 & num_boys == 0 ~ "Girls Only",
      TRUE ~ "Mixed"
    ),
    Label = paste0("(", School_Type, ")")
  )

#merge school type info with top 10 Data
top_data <- top_data %>%
  left_join(school_type_top %>% select(School_Id, Label), by = "School_Id") %>%
  mutate(School_Label = paste0(School_Id, "\n", Label))

#plotting boxplots for Scores by Gender in top 10 Schools 
ggplot(top_data, aes(x = reorder(School_Label, Scores), y = Scores, fill = Gender)) +
   geom_boxplot(position = position_dodge2(preserve="single"), alpha=0.7,
                outlier.shape = 21, color = "black",varwidth=TRUE) +
  labs(
    title = "Best Performed 10 Schools by Scores and Gender Dominance",
    x = "School ID (School Type)",
    y = "Scores"
  ) +
  scale_fill_manual(values = c("GIRL" = "lightpink", "BOY" = "steelblue")) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

#Combined plot of worst 10 schools by gender dominance
```{r}
#selected 10 schools out of all schools who performed worst.
bottom_10_schools <- cleaned_data %>%
  group_by(School_Id) %>%
  summarise(Mean_Score = mean(Scores, na.rm = TRUE)) %>%
  arrange(Mean_Score) %>%
  slice_head(n = 10)

#filtered the bottom 10 schools and assigned it to another variable 
bottom_data <- cleaned_data %>%
  filter(School_Id %in% bottom_10_schools$School_Id)

#select school type(Boys only/ Girls Only or Mixed)
school_type <- bottom_data %>%
  group_by(School_Id) %>%
  summarise(
    num_boys = sum(Gender == "BOY"),
    num_girls = sum(Gender == "GIRL")
  ) %>%
  mutate(
    School_Type = case_when(
      num_boys > 0 & num_girls == 0 ~ "Boys Only",
      num_girls > 0 & num_boys == 0 ~ "Girls Only",
      TRUE ~ "Mixed"
    ),
    Label = paste0("(", School_Type, ")")
  )

#merge school type info with bottom 10 Data
bottom_data <- bottom_data %>%
  left_join(school_type %>% select(School_Id, Label), by = "School_Id") %>%
  mutate(School_Label = paste0(School_Id, "\n", Label))

#plotting boxplots for Scores by Gender in worst 10 Schools 
ggplot(bottom_data, aes(x = reorder(School_Label, Scores), y = Scores, fill = Gender)) +
 geom_boxplot(position = position_dodge2(preserve="single"), alpha=0.7,
              outlier.shape = 21, color = "black",varwidth=TRUE)+
  labs(
    title = "Worst Performed 10 Schools by Scores and Gender Dominance",
    x = "School ID (School Type)",
    y = "Scores"
  ) +
  scale_fill_manual(values = c("GIRL" = "lightpink", "BOY" = "steelblue")) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

#Combined Plot of Gender-wise score distribution of selected variables

```{r}
#modified data for Parent_Educ and Parent_Support
long_data1 <- cleaned_data %>%
  mutate(across(c(Gender, Parent_Educ, Parent_Support), as.character)) %>%
  pivot_longer(
    cols = c(Parent_Educ, Parent_Support),
    names_to = "Variable",
    values_to = "Category"
  )

#set category levels for display in plots
long_data1 <- long_data1 %>%
  mutate(
    Category = case_when(
      Variable == "Parent_Educ" ~ factor(Category, levels = c("less than ISCED2", "ISCED2", "ISCED3", 
                   "ISCED4", "ISCED5", "ISCED6", "ISCED7 or 8")),
      Variable == "Parent_Support" ~ factor(Category,levels = c("VERY LOW", "LOW", "MEDIUM", "HIGH", 
                                                                "VERY HIGH")),
      TRUE ~ as.factor(Category)
    )
  )

#plotting boxplots for Gender-wise scores across categorical variables.
ggplot(long_data1, aes(x = Category, y = Scores, fill = Gender)) +
  geom_boxplot(position = position_dodge2(preserve="single"),#separate boxes for each gender
               alpha = 0.7,
               outlier.shape = 21, color = "black",varwidth=TRUE) +
  facet_wrap(~ Variable, scales = "free_x", nrow = 1) +
  labs(
    title = "Gender-wise Distribution of Scores by Categorical Variables",
    x = "Category", y = "Scores"
  ) +
  scale_fill_manual(values = c("GIRL" = "pink", "BOY" = "steelblue")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size =12),
    legend.position = "bottom",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 14)
  )
```
```{r}
#set data for Book_Availability and Teacher_Shortage
long_data2 <- cleaned_data %>%
  mutate(across(c(Gender, Book_Availability, Teacher_Shortage), as.character)) %>%
  pivot_longer(
    cols = c(Book_Availability, Teacher_Shortage),
    names_to = "Variable",
    values_to = "Category"
  )

#set category levels for display in plots
long_data2 <- long_data2 %>%
  mutate(
    Category = case_when(
      Variable == "Book_Availability" ~ factor(Category,levels = c("Few", "Moderate", "Good", 
                                                                   "Very Good",   "Excellent")),
      Variable == "Teacher_Shortage" ~ factor(Category,levels = c("None", "Low", "Moderate", "High")),
      TRUE ~ as.factor(Category)
    )
  )

#plotting boxplots for Gender-wise scores across categorical variables.
ggplot(long_data2, aes(x = Category, y = Scores, fill = Gender)) +
  geom_boxplot(position = position_dodge2(preserve="single"), alpha = 0.7,
               outlier.shape = 21, color = "black",varwidth=TRUE) +
  facet_wrap(~ Variable, scales = "free_x", nrow = 1) +
  labs(
    title = "Gender-wise Distribution of Scores by Categorical Variables",
    x = "Category", y = "Scores"
  ) +
  scale_fill_manual(values = c("GIRL" = "pink", "BOY" = "steelblue")) +
  theme_minimal() +
  theme(
     axis.text.x = element_text(angle = 45, hjust = 1, size =12),
    legend.position = "bottom",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 14)
  )
```
```{r}
#set data for Percent_Affluent and Percent_Disadvantaged
long_data3 <- cleaned_data %>%
  mutate(across(c(Gender, Percent_Affluent, Percent_Disadvantaged), as.character)) %>%
  pivot_longer(
    cols = c(Percent_Affluent, Percent_Disadvantaged),
    names_to = "Variable",
    values_to = "Category"
  )

#set category levels for display in plots
long_data3 <- long_data3 %>%
  mutate(
    Category = case_when(
     Variable == "Percent_Affluent" ~ factor(Category, 
                            levels = c("Low", "Moderate", "High", "Excellent")),
      Variable == "Percent_Disadvantaged" ~ factor(Category, 
        levels = c("Low", "Moderate", "High", "Severe")),
      TRUE ~ as.factor(Category)
    )
  )

#plotting boxplots for Gender-wise scores across categorical variables.
ggplot(long_data3, aes(x = Category, y = Scores, fill = Gender)) +
  geom_boxplot(position = position_dodge2(preserve="single"), alpha = 0.7, 
               outlier.shape = 21, color = "black",varwidth=TRUE)  +
  facet_wrap(~ Variable, scales = "free_x", nrow = 1) +
  labs(
    title = "Gender-wise Distribution of Scores by Categorical Variables",
    x = "Category", y = "Scores"
  ) +
  scale_fill_manual(values = c("GIRL" = "pink", "BOY" = "steelblue")) +
  theme_minimal() +
  theme(
     axis.text.x = element_text(angle = 45, hjust = 1, size =12),
    legend.position = "bottom",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 14)
  )
```
















